feat: hydrate Chat and User
grammyjs/hydrate pull request #18
Opened 2023-06-30 15:43 UTC by roziscoding

Closes #15

2023-07-04 12:55 UTC, roziscoding commented on src/data/chat-join-request.ts
> +import { installUserMethods, UserX } from "./user.ts";
```suggestion
import { UserX , installUserMethods } from "./user.ts";
```

2023-07-04 12:56 UTC, roziscoding commented on src/data/chat-join-request.ts
> +    & { chat: ChatX };
```suggestion
export type ChatJoinRequestX = & ChatJoinRequestXFragment & ChatJoinRequest;
```

2023-07-04 12:57 UTC, roziscoding commented on src/data/chat-join-request.ts
> +    installUserMethods(api, chatJoinRequest.from, chatJoinRequest.chat);
```suggestion
```

2023-07-04 12:58 UTC, roziscoding commented on src/data/chat-join-request.ts
> +export type ChatJoinRequestX = & ChatJoinRequestXFragment & ChatJoinRequest;
```suggestion
export type ChatJoinRequestX = ChatJoinRequestXFragment & ChatJoinRequest;
```

2023-07-04 12:58 UTC, roziscoding commented on src/data/chat-join-request.ts
> +import { UserX , installUserMethods } from "./user.ts";
```suggestion
```

2023-07-04 12:58 UTC, roziscoding commented on src/data/chat-join-request.ts
> +
```suggestion
```

2023-07-07 13:24 UTC, KnorpelSenf requested changes

2023-07-07 13:24 UTC, KnorpelSenf commented on deno.jsonc
> +        "backport": "deno run --no-prompt --allow-read=. --allow-write=. https://lib.deno.dev/x/deno2node@v1/src/cli.ts tsconfig.json",
We should pin the version of our build tooling. Otherwise, it may randomly break our setup.

2023-07-08 17:08 UTC, roziscoding commented on src/plugin.ts
> +            } else if (isChatMember(res.result) && hasChatId(payload)) {
I completely agree.
Would you rather I rewrite this portion of the code (including the pre-existing one) or do you think that's out of scope for this PR?

2023-07-08 17:14 UTC, roziscoding commented on src/plugin.ts
> +import { ChatX, installChatMethods } from "./data/chat.ts";
Done. Thanks!

2023-07-08 22:32 UTC, KnorpelSenf commented on src/plugin.ts
> +            } else if (isChatMember(res.result) && hasChatId(payload)) {
Your plugin, your PQ, your definition of the scope.

I personally would just fix it up right here.

2023-07-10 01:34 UTC, roziscoding commented on src/plugin.ts
> +            } else if (isChatMember(res.result) && hasChatId(payload)) {
Hm... TypeScript doesn't narrow the types if I do `if (method === 'getChat')`. Do you have any ideas on how we could do that?
I'll try again tomorrow but if it turns out to take too long I'll just move forward with the PQ and we can change this on a new one.

2023-07-11 17:08 UTC, roziscoding commented on src/plugin.ts
> +            } else if (isChatMember(res.result) && hasChatId(payload)) {
This unfortunately cannot be done currently AFAIK. We’ll move on with this PQ and open another one, if we ever find a better way of doing this.

2023-07-11 17:23 UTC, KnorpelSenf requested changes

2023-07-11 17:23 UTC, KnorpelSenf commented on .vscode/shortcuts.code-snippets
> +{
What is the point of this file?

2023-07-11 17:23 UTC, KnorpelSenf commented on src/plugin.ts
> +    Chat,
```suggestion
    type Chat,
```
and related changes

2023-07-11 19:58 UTC, KnorpelSenf commented on .vscode/shortcuts.code-snippets
> +{
Oof

2023-07-11 20:02 UTC, KnorpelSenf approved these changes
LGTM apart from the inconsistencies with imports

2023-07-11 20:03 UTC, KnorpelSenf commented
@KnightNiwrem @dcdunkan perhaps you guys still wanna TAL, I didn't test this

2023-10-11 17:31 UTC, KnightNiwrem approved these changes
TRUST

2023-10-14 09:32 UTC, merged

2023-12-30 19:44 UTC, KnorpelSenf commented
How is this still unreleased? That will happen today then.